# Makefile — command contract for the template repository itself.
# Projects generated by ./init.sh get their own Makefile with the same targets
# wired to their stack (see templates/common/Makefile.tpl).

SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

PYTHON ?= python3
SHELL_SOURCES := init.sh $(wildcard scripts/*.sh) $(wildcard .claude/hooks/*.sh)

.PHONY: help
help: ## Show the available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Nothing to install — the template has no runtime dependencies
	@echo "No dependencies. Requires: bash, git, python3 (sync + hook fallback)."

.PHONY: sync
sync: ## Regenerate the opencode artifacts from the Claude Code sources
	@$(PYTHON) scripts/sync-opencode.py

.PHONY: check-sync
check-sync: ## Fail if the generated opencode artifacts are out of date
	@$(PYTHON) scripts/sync-opencode.py --check

.PHONY: test-hooks
test-hooks: ## Prove the security guardrails actually fire
	@./scripts/test-hooks.sh

.PHONY: validate
validate: ## Validate JSON files, skill and agent frontmatter
	@./scripts/validate-template.sh

.PHONY: test
test: test-hooks ## Run the template test suite
	@./scripts/test-template.sh

.PHONY: lint
lint: ## Shellcheck every shell script (skipped if shellcheck is absent)
	@if command -v shellcheck >/dev/null 2>&1; then \
		shellcheck -x $(SHELL_SOURCES) && echo "shellcheck: clean"; \
	else \
		echo "shellcheck not installed — skipping (CI enforces it)"; \
	fi

.PHONY: typecheck
typecheck: ## Byte-compile the Python tooling
	@$(PYTHON) -m py_compile scripts/*.py && echo "python: clean"

.PHONY: build
build: ## Nothing to build — the template ships as source
	@echo "Nothing to build."

.PHONY: audit
audit: ## Dependency audit — the template has no third-party dependencies
	@echo "No third-party dependencies."

.PHONY: check
check: validate lint typecheck test check-sync ## Full quality gate
	@echo ""
	@echo "✅ quality gate green"

.PHONY: demo
demo: ## Bootstrap a throwaway project to inspect the output (STACK=python-fastapi)
	@rm -rf /tmp/vibe-demo
	@./init.sh demo $(or $(STACK),python-fastapi) /tmp/vibe-demo --yes
	@echo "→ /tmp/vibe-demo"
