# Makefile — command contract for the template repository itself.
# Projects generated by ./init.sh get their own Makefile with the same targets
# wired to their stack (see templates/common/Makefile.tpl).

SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

PYTHON ?= python3
SHELL_SOURCES := init.sh $(wildcard scripts/*.sh) $(wildcard scripts/scaffold/*.sh) $(wildcard .claude/hooks/*.sh)

# Python that init.sh copies into a generated project. It lands next to that
# project's own code and is linted by that project's linter, with that project's
# rules — so it has to pass them. The python-fastapi preset is the strictest one
# the template ships, which makes it the right yardstick.
VENDORED_PY := scripts/quorum.py
VENDORED_PY_CONFIG := templates/skeleton/python-fastapi/ruff.toml

.PHONY: help
help: ## Show the available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Nothing to install — the template has no runtime dependencies
	@echo "No dependencies. Requires: bash, git, python3 (sync + hook fallback)."

.PHONY: sync
sync: ## Regenerate the opencode artifacts from the Claude Code sources
	@$(PYTHON) scripts/sync-opencode.py

.PHONY: check-sync
check-sync: ## Fail if the generated opencode artifacts are out of date
	@$(PYTHON) scripts/sync-opencode.py --check

.PHONY: test-hooks
test-hooks: ## Prove the security guardrails actually fire
	@./scripts/test-hooks.sh

.PHONY: agents
agents: ## Show what the subagents have been doing (reads the ledger)
	@./scripts/show-ledger.sh

.PHONY: validate
validate: ## Validate JSON files, skill and agent frontmatter
	@./scripts/validate-template.sh

.PHONY: test-quorum
test-quorum: ## Prove the cohort's arithmetic (ADR-007)
	@./scripts/test-quorum.sh

.PHONY: test
test: test-hooks test-quorum ## Run the template test suite
	@./scripts/test-template.sh

.PHONY: lint
lint: ## Shellcheck every shell script (skipped if shellcheck is absent)
	@if command -v shellcheck >/dev/null 2>&1; then \
		LC_ALL=C.UTF-8 shellcheck -x -S warning $(SHELL_SOURCES) && echo "shellcheck: clean"; \
	else \
		echo "shellcheck not installed — skipping (CI enforces it)"; \
	fi
	@if command -v ruff >/dev/null 2>&1; then \
		ruff check --config $(VENDORED_PY_CONFIG) $(VENDORED_PY) >/dev/null \
		&& ruff format --config $(VENDORED_PY_CONFIG) --check $(VENDORED_PY) >/dev/null \
		&& echo "vendored python: clean under the shipped ruff config"; \
	else \
		echo "ruff not installed — skipping (the bootstrap matrix enforces it)"; \
	fi

.PHONY: typecheck
typecheck: ## Byte-compile the Python tooling
	@$(PYTHON) -m py_compile scripts/*.py && echo "python: clean"

.PHONY: build
build: ## Nothing to build — the template ships as source
	@echo "Nothing to build."

.PHONY: audit
audit: ## Dependency audit — the template has no third-party dependencies
	@echo "No third-party dependencies."

.PHONY: check
check: validate lint typecheck test check-sync ## Full quality gate
	@echo ""
	@echo "✅ quality gate green"

.PHONY: demo
demo: ## Bootstrap a throwaway project to inspect the output (STACK=python-fastapi)
	@rm -rf /tmp/vibe-demo
	@./init.sh demo $(or $(STACK),python-fastapi) /tmp/vibe-demo --yes
	@echo "→ /tmp/vibe-demo"
