# Makefile — the command contract every agent and every human uses (AGENTS.md B4).
# Generated by init.sh for the @@STACK@@ stack. Edit the recipes freely; keep the
# target names, they are what the agents, the CI pipeline and the docs rely on.

SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

.PHONY: help
help: ## Show the available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Install dependencies
	@@INSTALL@@

.PHONY: test
test: ## Run the test suite — required before every commit
	@@TEST@@

.PHONY: lint
lint: ## Lint and format check — zero warnings
	@@LINT@@

.PHONY: typecheck
typecheck: ## Static type check
	@@TYPECHECK@@

.PHONY: build
build: ## Full build
	@@BUILD@@

.PHONY: dev
dev: ## Run locally
	@@DEV@@

.PHONY: audit
audit: ## Dependency and CVE audit (AGENTS.md A13)
	@@AUDIT@@

.PHONY: check
check: lint typecheck test build ## The quality gate — run before every commit
	@echo ""
	@echo "✅ quality gate green"

.PHONY: sync
sync: ## Regenerate the opencode artifacts from the Claude Code sources
	@if [ -f scripts/sync-opencode.py ]; then python3 scripts/sync-opencode.py; else echo "sync not installed"; fi

.PHONY: check-sync
check-sync: ## Fail if the generated opencode artifacts are out of date
	@if [ -f scripts/sync-opencode.py ]; then python3 scripts/sync-opencode.py --check; else echo "sync not installed"; fi

.PHONY: test-hooks
test-hooks: ## Prove the security guardrails actually fire
	@if [ -f scripts/test-hooks.sh ]; then ./scripts/test-hooks.sh; else echo "hook tests not installed"; fi
