#!/usr/bin/env python3
"""sync-opencode.py — generate the opencode artifacts from the Claude Code sources.

One source per concept (rule A11):

    .claude/agents/*.md        ->  .opencode/agents/*.md
    .claude/skills/*/SKILL.md  ->  .opencode/commands/*.md   (thin wrappers)
    .claude/settings.json      ->  opencode.json  ["permission"]

Skills themselves are NOT copied: opencode reads `.claude/skills/` natively.

Run with --check to verify the generated files are up to date (used by CI).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BANNER = "<!-- GENERATED by scripts/sync-opencode.py from {source} — DO NOT EDIT. Run `make sync`. -->"

# ── Minimal frontmatter parsing (flat keys only — that is all we emit) ───────

def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end].strip("\n")
    body = text[end + 4 :].lstrip("\n")
    data: dict[str, str] = {}
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data, body


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


# ── Claude tool list -> opencode permission block ───────────────────────────

TOOL_ALIASES = {
    "read": "read", "glob": "glob", "grep": "grep", "list": "list",
    "write": "edit", "edit": "edit", "multiedit": "edit", "notebookedit": "edit",
    "bash": "bash", "webfetch": "webfetch", "websearch": "websearch",
    "task": "task", "agent": "task", "skill": "skill",
}

RULE_RE = re.compile(r"^([A-Za-z_]+)(?:\((.*)\)$)?")


def parse_rule(rule: str) -> tuple[str | None, str | None]:
    """'Bash(git log*)' -> ('bash', 'git log*')   ·   'Read' -> ('read', None)"""
    match = RULE_RE.match(rule.strip())
    if not match:
        return None, None
    return TOOL_ALIASES.get(match.group(1).lower()), match.group(2)


def agent_permission(tools: str) -> dict[str, object]:
    """Translate a Claude `tools:` allowlist into an opencode permission block."""
    granted: dict[str, list[str]] = {}
    for entry in re.findall(r"[A-Za-z_]+(?:\([^)]*\))?", tools or ""):
        tool, spec = parse_rule(entry)
        if not tool:
            continue
        granted.setdefault(tool, [])
        if spec:
            granted[tool].append(spec)

    permission: dict[str, object] = {}
    # A Claude `tools:` list is an allowlist: anything absent is denied.
    for tool in ("edit", "bash", "webfetch", "websearch", "task"):
        if tool not in granted:
            permission[tool] = "deny"
    for tool, specs in granted.items():
        if not specs:
            permission[tool] = "allow"
        else:
            block: dict[str, str] = {"*": "deny"}
            for spec in specs:
                block[spec] = "allow"
            permission[tool] = block
    # Reading the codebase is always allowed for a subagent.
    for tool in ("read", "glob", "grep", "list"):
        permission.setdefault(tool, "allow")
    return permission


def yaml_permission(permission: dict[str, object], indent: str = "  ") -> str:
    lines = ["permission:"]
    for key in sorted(permission):
        value = permission[key]
        if isinstance(value, dict):
            lines.append(f"{indent}{key}:")
            for pattern, action in value.items():
                lines.append(f'{indent}{indent}"{pattern}": {action}')
        else:
            lines.append(f"{indent}{key}: {value}")
    return "\n".join(lines)


# ── Generators ──────────────────────────────────────────────────────────────

def build_agents() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for source in sorted((ROOT / ".claude" / "agents").glob("*.md")):
        meta, body = split_frontmatter(source.read_text(encoding="utf-8"))
        name = meta.get("name", source.stem)
        description = meta.get("description", "")
        # `model` is deliberately dropped: an opencode subagent inherits the model
        # of the primary agent that invoked it, and Claude's aliases (opus, sonnet)
        # are not valid provider/model ids here.
        frontmatter = [
            "---",
            f"description: {yaml_quote(description)}",
            "mode: subagent",
            "temperature: 0.1",
            yaml_permission(agent_permission(meta.get("tools", ""))),
            "---",
        ]
        rel = source.relative_to(ROOT)
        content = "\n".join(frontmatter) + "\n\n" + BANNER.format(source=rel) + "\n\n" + body.rstrip() + "\n"
        out[ROOT / ".opencode" / "agents" / f"{name}.md"] = content
    return out


def build_commands() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for source in sorted((ROOT / ".claude" / "skills").glob("*/SKILL.md")):
        meta, _ = split_frontmatter(source.read_text(encoding="utf-8"))
        name = meta.get("name", source.parent.name)
        description = meta.get("description", "")
        rel = source.relative_to(ROOT)
        content = (
            "---\n"
            f"description: {yaml_quote(description)}\n"
            "---\n\n"
            f"{BANNER.format(source=rel)}\n\n"
            f"Follow the instructions in @{rel} and apply them to the request below.\n\n"
            "Request: $ARGUMENTS\n"
        )
        out[ROOT / ".opencode" / "commands" / f"{name}.md"] = content
    return out


def build_permission() -> dict[str, object]:
    settings = json.loads((ROOT / ".claude" / "settings.json").read_text(encoding="utf-8"))
    perms = settings.get("permissions", {})

    scalars: dict[str, str] = {}
    patterns: dict[str, dict[str, str]] = {}
    # Order matters: opencode applies the LAST matching rule, so allow first,
    # then ask, then deny — a deny always wins over a broader allow.
    for action in ("allow", "ask", "deny"):
        for rule in perms.get(action, []):
            tool, spec = parse_rule(rule)
            if not tool:
                continue
            if spec:
                patterns.setdefault(tool, {})[spec] = action
            else:
                scalars[tool] = action

    permission: dict[str, object] = {}
    for tool, block in patterns.items():
        # `read` is allow-by-default in opencode; everything else asks first.
        default = "allow" if tool in ("read", "glob", "grep", "list") else "ask"
        permission[tool] = {"*": scalars.pop(tool, default), **block}
    permission.update(scalars)
    permission.setdefault("skill", "allow")
    permission.setdefault("edit", "ask")
    return {key: permission[key] for key in sorted(permission)}


def build_opencode_json() -> str:
    path = ROOT / "opencode.json"
    config = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    config["permission"] = build_permission()
    return json.dumps(config, indent=2, ensure_ascii=False) + "\n"


# ── Entry point ─────────────────────────────────────────────────────────────

def main() -> int:
    check = "--check" in sys.argv
    generated = {**build_agents(), **build_commands()}
    generated[ROOT / "opencode.json"] = build_opencode_json()

    expected_dirs = {ROOT / ".opencode" / "agents", ROOT / ".opencode" / "commands"}
    stale = [
        path
        for directory in expected_dirs
        if directory.exists()
        for path in directory.glob("*.md")
        if path not in generated
    ]

    drift: list[str] = []
    for path, content in sorted(generated.items()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        drift.append(str(path.relative_to(ROOT)))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    for path in stale:
        drift.append(f"{path.relative_to(ROOT)} (stale)")
        if not check:
            path.unlink()

    if check:
        if drift:
            print("opencode artifacts are out of date:", file=sys.stderr)
            for item in drift:
                print(f"  - {item}", file=sys.stderr)
            print("\nRun `make sync` and commit the result.", file=sys.stderr)
            return 1
        print(f"opencode artifacts up to date ({len(generated)} files)")
        return 0

    if drift:
        print(f"synced {len(drift)} file(s):")
        for item in drift:
            print(f"  - {item}")
    else:
        print(f"already in sync ({len(generated)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
